# PyChat stub — Reforged Native surface
# Matches src/GW/chat/chat_bindings.cpp (module-level free functions only;
# the GW::chat::Channel enum is NOT bound — channels are plain ints).

def force_redraw_chat_log() -> None: ...
def get_is_typing() -> bool: ...
def send_chat(channel: int, msg: str) -> bool:
    """Send a chat message on a channel (channel is cast to char, e.g. ord('!')/ord('#'))."""
    ...

def send_chat_by_name(sender: str, msg: str) -> bool:
    """Whisper: send `msg` to the named target. Bound as py::arg("from")."""
    ...

def write_chat(channel: int, message: str) -> None:
    """Write a local-only message to the chat log."""
    ...

def write_chat_ex(channel: int, message: str, sender: str) -> None:
    """Write a local-only message to the chat log with an explicit sender."""
    ...

def toggle_timestamps(enable: bool) -> None: ...
def set_timestamps_format(use_24h: bool, show_seconds: bool = False) -> None: ...
def set_timestamps_color(r: int, g: int, b: int) -> None: ...
def set_sender_color(channel: int, r: int, g: int, b: int) -> None: ...
def set_message_color(channel: int, r: int, g: int, b: int) -> None: ...
def send_fake_chat(channel: int, message: str) -> None: ...
def send_fake_chat_colored(channel: int, message: str, r: int, g: int, b: int) -> None: ...
