# PyFriendList stub — Reforged Native surface
# Matches src/GW/friend_list/friend_list_bindings.cpp.
# FriendType / FriendStatus are NOT bound as enums — they are plain ints
# (see GW::Constants::FriendType / FriendStatus).
# Mutating calls are game-thread enqueued and return True immediately.

def get_number_of_friends(friend_type: int = 1) -> int: ...
def get_number_of_ignores() -> int: ...
def get_number_of_partners() -> int: ...
def get_number_of_traders() -> int: ...
def get_my_status() -> int: ...
def set_friend_list_status(status: int) -> bool: ...
def add_friend(name: str, alias: str = "") -> bool: ...
def add_ignore(name: str, alias: str = "") -> bool: ...
