# PyGuild stub — Reforged Native surface
# Matches src/GW/guild/guild_bindings.cpp.
# travel_gh/leave_gh are game-thread enqueued and return True immediately.

def get_player_guild_index() -> int: ...
def get_player_guild_announcement() -> str: ...
def get_player_guild_announcer() -> str: ...
def travel_gh() -> bool: ...
def leave_gh() -> bool: ...
