# PyInventory stub — Reforged Native surface (2026-07-20)
# Exact counterpart of src/GW/item/inventory_bindings.cpp. Bag + PyInventory classes.
# NOTE: IsSalvaging(), IsSalvageTransactionDone(), FinishSalvage() NOT in Reforged.
#       GetItemByIndex(), FindItemById() NOT in Reforged Bag.
# NOTE: every PyInventory action is queued on the game thread and returns None.

from typing import Any
from typing import Dict
from typing import List

class Bag:
    id: int
    name: str
    container_item: int
    items_count: int
    is_inventory_bag: bool
    is_storage_bag: bool
    is_material_storage: bool

    def __init__(self, id: int, name: str = "") -> None: ...
    # entries: {"item_id": int, "slot": int, "model_id": int, "quantity": int}
    def GetItems(self) -> List[Dict[str, Any]]: ...
    def GetItemCount(self) -> int: ...
    def GetSize(self) -> int: ...
    def GetContext(self) -> None: ...

class PyInventory:
    def __init__(self) -> None: ...
    def OpenXunlaiWindow(self) -> None: ...
    def GetIsStorageOpen(self) -> bool: ...
    def PickUpItem(self, item_id: int, call_target: bool = False) -> None: ...
    def DropItem(self, item_id: int, quantity: int = 1) -> None: ...
    def EquipItem(self, item_id: int, agent_id: int) -> None: ...
    def UseItem(self, item_id: int) -> None: ...
    def DestroyItem(self, item_id: int) -> None: ...
    def IdentifyItem(self, id_kit_id: int, item_id: int) -> None: ...
    def GetHoveredItemID(self) -> int: ...
    def GetGoldAmount(self) -> int: ...
    def GetGoldAmountInStorage(self) -> int: ...
    def DepositGold(self, amount: int) -> None: ...
    def WithdrawGold(self, amount: int) -> None: ...
    def DropGold(self, amount: int) -> None: ...
    def MoveItem(self, item_id: int, bag_id: int, slot: int, quantity: int = 1) -> None: ...
    def Salvage(self, salv_kit_id: int, item_id: int) -> None: ...
    def AcceptSalvageWindow(self) -> None: ...

# ── Modern dict-based surface ──
# get_bag keys: id, items_count, container_item, size, is_inventory_bag,
# is_storage_bag, is_material_storage, items (list of
# {"item_id", "slot", "model_id", "quantity"}).
def get_bag(bag_id: int) -> Dict[str, Any]: ...
def get_hovered_item_id() -> int: ...
def salvage(salv_kit_id: int, item_id: int) -> None: ...
def accept_salvage_window() -> None: ...
