# PyMerchant.pyi - type stub for the PyMerchant embedded module.
#
# Mirrors src/GW/merchant/merchant_bindings.cpp exactly: the legacy PyMerchant
# class surface plus the two reforged free functions. No enums are exposed by
# this module (TransactionType lives in the Python-side enums).

from typing import List

class PyMerchant:
    def __init__(self) -> None: ...
    # --- Trader (buy/sell tab) ---
    def trader_buy_item(self, item_id: int, cost: int) -> bool: ...
    def trader_sell_item(self, item_id: int, price: int) -> bool: ...
    def trader_request_quote(self, item_id: int) -> bool: ...
    def trader_request_sell_quote(self, item_id: int) -> bool: ...
    # --- Merchant (materials / rune trader) ---
    def merchant_buy_item(self, item_id: int, cost: int) -> bool: ...
    def merchant_sell_item(self, item_id: int, price: int) -> bool: ...
    # --- Crafter / Collector (give_item_ids and give_item_quantities must be same length) ---
    def crafter_buy_item(
        self, item_id: int, cost: int, give_item_ids: List[int], give_item_quantities: List[int]
    ) -> bool: ...
    def collector_buy_item(
        self, item_id: int, cost: int, give_item_ids: List[int], give_item_quantities: List[int]
    ) -> bool: ...
    # --- State getters (backed by the merchant listener) ---
    def get_trader_item_list(self) -> List[int]: ...
    def get_trader_item_list2(self) -> List[int]: ...  # always empty (legacy never populated it)
    def get_merchant_item_list(self) -> List[int]: ...
    def get_quoted_value(self) -> int: ...
    def get_quoted_item_id(self) -> int: ...
    def is_transaction_complete(self) -> bool: ...
    def update(self) -> None: ...  # no-op; state is refreshed by the listeners

# --- Modern free-function surface (reforged additions) ---

# `type` is a GW::Constants::TransactionType value. give/recv id and quantity
# lists are truncated to the shorter of each pair.
def transact_items(
    type: int,
    gold_give: int = 0,
    give_item_ids: List[int] = ...,
    give_quantities: List[int] = ...,
    gold_recv: int = 0,
    recv_item_ids: List[int] = ...,
    recv_quantities: List[int] = ...,
) -> bool: ...
def request_quote(type: int, give_item_ids: List[int] = ..., recv_item_ids: List[int] = ...) -> bool: ...
