# PyOverlay stub - Reforged Native surface.
# Matches overlay_bindings.cpp. Vec2f/Vec3f replace legacy Point2D/Point3D.

from typing import List, Tuple, overload

class Vec2f:
    x: float  # X coordinate
    y: float  # Y coordinate
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...

class Vec3f:
    x: float  # X coordinate
    y: float  # Y coordinate
    z: float  # Z coordinate
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float = 0.0) -> None: ...

class Overlay:
    def __init__(self) -> None: ...
    def RefreshDrawList(self) -> None: ...
    def GetMouseCoords(self) -> Vec2f: ...

    # --- ground height / z-planes -------------------------------------------
    # multi_plane=True (default): topmost surface across ALL planes (bridges/slopes
    # are planes > 0), stable regardless of the player's plane.
    # multi_plane=False: legacy altitude at the player's plane.
    def FindZ(self, x: float, y: float, pz: int = 0, multi_plane: bool = True) -> float: ...
    # Batched FindZ (path display, dozens/frame): plane list fetched once, single-plane fast path.
    def FindZBatch(self, points: List[Tuple[float, float]], multi_plane: bool = True) -> List[float]: ...
    def FindZPlane(self, x: float, y: float, z: int = 0) -> int: ...
    # Number of z-planes (pmaps); 0 if not ready. <= 1 => single-plane (cheap gate).
    def GetZPlaneCount(self) -> int: ...
    # Altitude at a SPECIFIC plane -> (covered, z). covered=False if no surface there.
    def QueryAltitudeAt(self, x: float, y: float, plane: int) -> Tuple[bool, float]: ...
    # Specialist: covered surface nearest ref_z (bridge-over vs under-bridge).
    def GroundZNearest(self, x: float, y: float, ref_z: float) -> float: ...
    def GroundZNearestBatch(self, points: List[Tuple[float, float]], ref_zs: List[float]) -> List[float]: ...
    # Option B: plane-less navmesh/terrain height (does NOT add bridge/slope props).
    def GroundZWalkable(self, x: float, y: float) -> float: ...
    def GroundZWalkableBatch(self, points: List[Tuple[float, float]]) -> List[float]: ...

    # --- coordinate conversions ---------------------------------------------
    def WorldToScreen(self, x: float, y: float, z: float) -> Vec2f: ...
    def GetMouseWorldPos(self) -> Vec3f: ...
    def GamePosToWorldMap(self, x: float, y: float) -> Vec2f: ...
    def WorldMapToGamePos(self, x: float, y: float) -> Vec2f: ...
    def WorldMapToScreen(self, x: float, y: float) -> Vec2f: ...
    def ScreenToWorldMap(self, x: float, y: float) -> Vec2f: ...
    def GameMapToScreen(self, x: float, y: float) -> Vec2f: ...
    def ScreenToGameMapPos(self, x: float, y: float) -> Vec2f: ...
    def NormalizedScreenToScreen(self, norm_x: float, norm_y: float) -> Vec2f: ...
    def ScreenToNormalizedScreen(self, screen_x: float, screen_y: float) -> Vec2f: ...
    def NormalizedScreenToWorldMap(self, norm_x: float, norm_y: float) -> Vec2f: ...
    def NormalizedScreenToGameMap(self, norm_x: float, norm_y: float) -> Vec2f: ...
    def GamePosToNormalizedScreen(self, x: float, y: float) -> Vec2f: ...

    # --- immediate-mode drawing ---------------------------------------------
    # Three distinct C++ overloads: no args / name only / name + bounds.
    @overload
    def BeginDraw(self) -> None: ...
    @overload
    def BeginDraw(self, name: str) -> None: ...
    @overload
    def BeginDraw(self, name: str, x: float, y: float, width: float, height: float) -> None: ...
    def EndDraw(self) -> None: ...
    # NOTE: the binding names the first parameter "from" (a Python keyword), so it
    # can only be passed positionally; spelled from_ here.
    def DrawLine(self, from_: Vec2f, to: Vec2f, color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawLine3D(self, from_: Vec3f, to: Vec3f, color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawTriangle(
        self, p1: Vec2f, p2: Vec2f, p3: Vec2f, color: int = 0xFFFFFFFF, thickness: float = 1.0
    ) -> None: ...
    def DrawTriangle3D(
        self, p1: Vec3f, p2: Vec3f, p3: Vec3f, color: int = 0xFFFFFFFF, thickness: float = 1.0
    ) -> None: ...
    def DrawTriangleFilled(self, p1: Vec2f, p2: Vec2f, p3: Vec2f, color: int = 0xFFFFFFFF) -> None: ...
    def DrawTriangleFilled3D(self, p1: Vec3f, p2: Vec3f, p3: Vec3f, color: int = 0xFFFFFFFF) -> None: ...
    def DrawQuad(
        self, p1: Vec2f, p2: Vec2f, p3: Vec2f, p4: Vec2f, color: int = 0xFFFFFFFF, thickness: float = 1.0
    ) -> None: ...
    def DrawQuad3D(
        self, p1: Vec3f, p2: Vec3f, p3: Vec3f, p4: Vec3f, color: int = 0xFFFFFFFF, thickness: float = 1.0
    ) -> None: ...
    def DrawQuadFilled(self, p1: Vec2f, p2: Vec2f, p3: Vec2f, p4: Vec2f, color: int = 0xFFFFFFFF) -> None: ...
    def DrawQuadFilled3D(self, p1: Vec3f, p2: Vec3f, p3: Vec3f, p4: Vec3f, color: int = 0xFFFFFFFF) -> None: ...
    def DrawPoly(
        self, center: Vec2f, radius: float, color: int = 0xFFFFFFFF, numSegments: int = 12, thickness: float = 1.0
    ) -> None: ...
    def DrawPoly3D(
        self,
        center: Vec3f,
        radius: float,
        color: int = 0xFFFFFFFF,
        numSegments: int = 12,
        thickness: float = 1.0,
        autoZ: bool = True,
    ) -> None: ...
    def DrawPolyFilled(self, center: Vec2f, radius: float, color: int = 0xFFFFFFFF, numSegments: int = 12) -> None: ...
    def DrawPolyFilled3D(
        self, center: Vec3f, radius: float, color: int = 0xFFFFFFFF, numSegments: int = 12, autoZ: bool = True
    ) -> None: ...
    def DrawCubeOutline(self, center: Vec3f, size: float, color: int = 0xFFFFFFFF, thickness: float = 1.0) -> None: ...
    def DrawCubeFilled(self, center: Vec3f, size: float, color: int = 0xFFFFFFFF) -> None: ...
    def DrawText(
        self, position: Vec2f, text: str, color: int = 0xFFFFFFFF, centered: bool = True, scale: float = 1.0
    ) -> None: ...
    def DrawText3D(
        self,
        position3D: Vec3f,
        text: str,
        color: int = 0xFFFFFFFF,
        autoZ: bool = True,
        centered: bool = True,
        scale: float = 1.0,
    ) -> None: ...
    def GetDisplaySize(self) -> Vec2f: ...
    def IsMouseClicked(self, button: int = 0) -> bool: ...
    def PushClipRect(self, x: float, y: float, x2: float, y2: float) -> None: ...
    def PopClipRect(self) -> None: ...

    # --- textures ------------------------------------------------------------
    @overload
    def DrawTexture(self, path: str, width: float = 32.0, height: float = 32.0) -> None: ...
    @overload
    def DrawTexture(
        self,
        path: str,
        size: Tuple[float, float] = (32.0, 32.0),
        uv0: Tuple[float, float] = (0.0, 0.0),
        uv1: Tuple[float, float] = (1.0, 1.0),
        tint: Tuple[int, int, int, int] = (255, 255, 255, 255),
        border_col: Tuple[int, int, int, int] = (0, 0, 0, 0),
    ) -> None: ...
    @overload
    def DrawTexturedRect(self, x: float, y: float, width: float, height: float, texture_path: str) -> None: ...
    @overload
    def DrawTexturedRect(
        self,
        pos: Tuple[float, float],
        size: Tuple[float, float],
        texture_path: str,
        uv0: Tuple[float, float] = (0.0, 0.0),
        uv1: Tuple[float, float] = (1.0, 1.0),
        tint: Tuple[int, int, int, int] = (255, 255, 255, 255),
    ) -> None: ...
    def UpkeepTextures(self, timeout: int = 30) -> None: ...
    @overload
    def ImageButton(
        self, caption: str, file_path: str, width: float = 32.0, height: float = 32.0, frame_padding: int = 0
    ) -> bool: ...
    @overload
    def ImageButton(
        self,
        caption: str,
        file_path: str,
        size: Tuple[float, float] = (32.0, 32.0),
        uv0: Tuple[float, float] = (0.0, 0.0),
        uv1: Tuple[float, float] = (1.0, 1.0),
        bg_color: Tuple[int, int, int, int] = (0, 0, 0, 0),
        tint_color: Tuple[int, int, int, int] = (255, 255, 255, 255),
        frame_padding: int = 0,
    ) -> bool: ...
    def DrawTextureInForegound(
        self,
        pos: Tuple[float, float] = (0.0, 0.0),
        size: Tuple[float, float] = (100.0, 100.0),
        texture_path: str = "",
        uv0: Tuple[float, float] = (0.0, 0.0),
        uv1: Tuple[float, float] = (1.0, 1.0),
        tint: Tuple[int, int, int, int] = (255, 255, 255, 255),
    ) -> None: ...
    def DrawTextureInDrawlist(
        self,
        pos: Tuple[float, float] = (0.0, 0.0),
        size: Tuple[float, float] = (100.0, 100.0),
        texture_path: str = "",
        uv0: Tuple[float, float] = (0.0, 0.0),
        uv1: Tuple[float, float] = (1.0, 1.0),
        tint: Tuple[int, int, int, int] = (255, 255, 255, 255),
    ) -> None: ...

# Desktop-level (GDI+) overlay: transparent, click-through, topmost layered window
# spanning the monitor; independent of the game window and Direct3D.
class ScreenOverlay:
    def __init__(self) -> None: ...
    # Create a transparent, click-through, topmost desktop overlay on the primary monitor.
    def create_overlay(self, ms: int = 0, destroy: bool = False) -> bool: ...
    def destroy(self) -> None: ...
    # Show or hide the desktop overlay window without activating it.
    def show(self, show: bool) -> None: ...
    # Begin a new frame (clears to fully transparent).
    def begin(self) -> None: ...
    # Desktop pixels; color is 0xAARRGGBB.
    def draw_rect(self, x: int, y: int, w: int, h: int, argb: int, thickness: float = 1.0) -> None: ...
    def draw_rect_filled(self, x: int, y: int, w: int, h: int, argb: int) -> None: ...
    # Text within a rectangle in desktop pixels; clipped/ellipsized if too long.
    # px_size is in pixels.
    def draw_text_box(
        self,
        x: int,
        y: int,
        w: int,
        h: int,
        text: str,
        argb: int,
        px_size: float,
        family: str = "Segoe UI",
        hcenter: bool = False,
        vcenter: bool = False,
    ) -> None: ...
    # Present the frame to the desktop using UpdateLayeredWindow.
    def end(self) -> None: ...
    # Size of the entire virtual desktop (all monitors) -> (width, height).
    def get_desktop_size(self) -> Tuple[int, int]: ...
    # ms=0 disables auto-expire. destroy=True destroys the window on expiry, else hides it.
    def set_auto_expire(self, ms: int, destroy: bool = False) -> None: ...
