# PyQuest stub — Reforged Native surface.
# Exact counterpart of src/GW/quest/quest_bindings.cpp.
# The quest *data* half (quest log rows) is read from the ctypes contexts
# (WorldContext.quest_log); what is bound here are the game-side operations and the
# async string decoders (name/description/objectives/location/npc).

from typing import List

class QuestData:
    quest_id: int
    log_state: int
    location: str
    name: str
    npc: str
    map_from: int
    marker_x: float
    marker_y: float
    h0024: int
    map_to: int
    description: str
    objectives: str
    is_completed: bool
    is_current_mission_quest: bool
    is_area_primary: bool
    is_primary: bool

    def __init__(self) -> None: ...

class PyQuest:
    def __init__(self) -> None: ...
    @staticmethod
    def set_active_quest_id(quest_id: int) -> bool: ...
    @staticmethod
    def get_active_quest_id() -> int: ...
    @staticmethod
    def abandon_quest_id(quest_id: int) -> bool: ...
    @staticmethod
    def is_quest_completed(quest_id: int) -> bool: ...
    @staticmethod
    def is_quest_primary(quest_id: int) -> bool: ...
    @staticmethod
    def is_mission_map_quest_available() -> bool: ...
    @staticmethod
    def get_quest_data(quest_id: int) -> QuestData: ...
    @staticmethod
    def get_quest_log() -> List[QuestData]: ...
    @staticmethod
    def get_quest_log_ids() -> List[int]: ...
    @staticmethod
    def request_quest_info(quest_id: int, update_markers: bool = False) -> bool: ...
    @staticmethod
    def request_quest_name(quest_id: int) -> None: ...
    @staticmethod
    def is_quest_name_ready(quest_id: int) -> bool: ...
    @staticmethod
    def get_quest_name(quest_id: int) -> str: ...
    @staticmethod
    def request_quest_description(quest_id: int) -> None: ...
    @staticmethod
    def is_quest_description_ready(quest_id: int) -> bool: ...
    @staticmethod
    def get_quest_description(quest_id: int) -> str: ...
    @staticmethod
    def request_quest_objectives(quest_id: int) -> None: ...
    @staticmethod
    def is_quest_objectives_ready(quest_id: int) -> bool: ...
    @staticmethod
    def get_quest_objectives(quest_id: int) -> str: ...
    @staticmethod
    def request_quest_location(quest_id: int) -> None: ...
    @staticmethod
    def is_quest_location_ready(quest_id: int) -> bool: ...
    @staticmethod
    def get_quest_location(quest_id: int) -> str: ...
    @staticmethod
    def request_quest_npc(quest_id: int) -> None: ...
    @staticmethod
    def is_quest_npc_ready(quest_id: int) -> bool: ...
    @staticmethod
    def get_quest_npc(quest_id: int) -> str: ...

# ── Module-level free functions ──
# NOTE: get_quest_data / get_quest_log exist ONLY on the PyQuest class, not here.
def set_active_quest_id(quest_id: int) -> bool: ...
def abandon_quest_id(quest_id: int) -> bool: ...
def get_active_quest_id() -> int: ...
def request_quest_info(quest_id: int, update_markers: bool = False) -> bool: ...
def get_quest_entry_group_name(quest_id: int) -> str: ...
def is_quest_completed(quest_id: int) -> bool: ...
def is_quest_primary(quest_id: int) -> bool: ...
def is_mission_map_quest_available() -> bool: ...
def get_quest_log_ids() -> List[int]: ...
def request_quest_name(quest_id: int) -> None: ...
def is_quest_name_ready(quest_id: int) -> bool: ...
def get_quest_name(quest_id: int) -> str: ...
def request_quest_description(quest_id: int) -> None: ...
def is_quest_description_ready(quest_id: int) -> bool: ...
def get_quest_description(quest_id: int) -> str: ...
def request_quest_objectives(quest_id: int) -> None: ...
def is_quest_objectives_ready(quest_id: int) -> bool: ...
def get_quest_objectives(quest_id: int) -> str: ...
def request_quest_location(quest_id: int) -> None: ...
def is_quest_location_ready(quest_id: int) -> bool: ...
def get_quest_location(quest_id: int) -> str: ...
def request_quest_npc(quest_id: int) -> None: ...
def is_quest_npc_ready(quest_id: int) -> bool: ...
def get_quest_npc(quest_id: int) -> str: ...
