# PyRender stub - Reforged Native surface.
# Matches GW/render/render_bindings.cpp ("Py4GW Render bindings").
# Only these five free functions are exposed; the rest of GW::render (device,
# window handle, transforms, render callbacks) is C++-only.

def get_is_in_render_loop() -> bool: ...

# Non-zero when the client is running fullscreen (GetIsFullscreen returns int).
def get_is_fullscreen() -> int: ...
def get_viewport_width() -> int: ...
def get_viewport_height() -> int: ...
def get_field_of_view() -> float: ...
