# PyTrade stub — Reforged Native surface
# Matches src/GW/trade/trade_bindings.cpp.
# open_trade_window is game-thread enqueued and returns True immediately.

def open_trade_window(agent_id: int) -> bool: ...
def accept_trade() -> bool: ...
def cancel_trade() -> bool: ...
def change_offer() -> bool: ...
def submit_offer(gold: int) -> bool: ...
def remove_item(slot: int) -> bool: ...
def offer_item(item_id: int, quantity: int = 0) -> bool: ...
def is_item_offered(item_id: int) -> bool: ...
