from typing import Optional, Iterator, TypeVar, Generic
from ctypes import Structure

class GW_TLink(Structure):
    prev_link: int
    next_node: int

    def IsLinked(self) -> bool: ...
    def Next(self, elem_type: type) -> Optional[Structure]: ...
    def Prev(self, elem_type: type) -> Optional[Structure]: ...
    def NextLink(self, elem_type: type, offset: int) -> Optional[int]: ...
    def PrevLink(self) -> int: ...

class GW_TList(Structure):
    offset: int
    link: GW_TLink

T = TypeVar("T")

class GW_TList_View(Generic[T]):
    def __init__(self, lst: GW_TList, elem_type: type[T]) -> None: ...
    def valid(self) -> bool: ...
    def size(self) -> int: ...
    def capacity(self) -> int: ...
    def get(self, index: int) -> Optional[T]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> T: ...
    def __iter__(self) -> Iterator[T]: ...
    def __reversed__(self) -> Iterator[T]: ...
    def to_list(self) -> list[T]: ...
