"""Regenerate .claude/LINE_INDEX.md — a navigation aid for the whole repo.

Walks the workspace for .py files (skipping virtualenvs, caches, and build
output) and scans each for ``class`` and top-level / single-indent ``def``
statements. Writes a per-file section with line numbers, so Claude (or a
grep-ing human) can jump straight to a definition.

The index deliberately covers the entire repo, not just files you own. Lint
scope and navigation scope are different problems: you don't want red squiggles
in someone else's code (that's what the allowlist is for), but you *do* want
to find things fast when reading unfamiliar code.

Output lands in .claude/LINE_INDEX.md, which is git-ignored via
.git/info/exclude — private to this clone, never reaches the shared repo.

Called by the pre-commit, post-checkout, post-rewrite and post-merge hooks so
the index stays fresh across normal commits, branch switches, rebases
(post-rewrite fires after `git rebase` and `git commit --amend`), and
merges/pulls.

Runs manually with:
    python tools/generate_line_index.py
"""
import re
import sys
from pathlib import Path


WORKSPACE_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = WORKSPACE_ROOT / ".claude" / "LINE_INDEX.md"

# Directory names we never want to descend into. Matched against any path
# component, so ``foo/bar/__pycache__/x.py`` is skipped by ``__pycache__``.
SKIP_DIR_NAMES = frozenset({
    ".git",
    ".venv",
    "venv",
    ".vscode",
    ".claude",
    "__pycache__",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".pytest_cache",
    "node_modules",
    "build",
    "dist",
    ".backups",
    ".opencode",
})


# Dunders are noise — the interesting surface is public API + typed constructors.
SKIP_DEFS = {
    "__init__",
    "__str__",
    "__repr__",
    "__bool__",
    "__len__",
    "__eq__",
    "__hash__",
    "__lt__",
    "__gt__",
    "__new__",
    "__enter__",
    "__exit__",
    "__iter__",
    "__next__",
}


def _iter_repo_py_files():
    """Yield every .py file in the workspace, skipping virtualenvs and caches."""
    for p in WORKSPACE_ROOT.rglob("*.py"):
        rel_parts = p.relative_to(WORKSPACE_ROOT).parts
        if any(part in SKIP_DIR_NAMES for part in rel_parts):
            continue
        yield p


def _extract_signatures(filepath):
    """Return [(line_num, [sig_line, ...]), ...] for classes and non-dunder defs.

    Handles multi-line signatures by keeping continuation lines until the
    opening paren is matched.
    """
    results = []
    lines = filepath.read_text(encoding="utf-8", errors="replace").splitlines()

    i = 0
    while i < len(lines):
        stripped = lines[i].rstrip()
        # Top-level class/def or single-indent def (methods on a class).
        if re.match(r"^(class |    def |def )", stripped):
            line_num = i + 1
            sig_lines = [stripped]

            # Continue reading if the paren list wasn't closed on this line.
            if "(" in stripped and ")" not in stripped:
                j = i + 1
                while j < len(lines):
                    cont = lines[j].rstrip()
                    sig_lines.append(cont)
                    if ")" in cont:
                        break
                    j += 1

            name_match = re.match(r"(?:class|def)\s+(\w+)", sig_lines[0].strip())
            if name_match and name_match.group(1) in SKIP_DEFS:
                i += 1
                continue

            results.append((line_num, sig_lines))
        i += 1
    return results


SIG_MAX_CHARS = 100


def _render_file_section(filepath):
    """Return a compact plain-text block for one file, or "" if nothing to index.

    Format is optimized for token cost, not Markdown rendering: each entry is a
    single ``L<line> <signature>`` line, multi-line signatures collapsed with
    ``...`` if they overflow ``SIG_MAX_CHARS``. Nobody's rendering this — the
    only consumers are grep and Claude.
    """
    rel = filepath.relative_to(WORKSPACE_ROOT).as_posix()
    line_count = sum(1 for _ in filepath.open("r", encoding="utf-8", errors="replace"))
    sigs = _extract_signatures(filepath)
    if not sigs:
        return ""

    out = [f"## {rel} ({line_count})"]
    for num, sig_lines in sigs:
        one = " ".join(sl.strip() for sl in sig_lines).strip()
        if len(one) > SIG_MAX_CHARS:
            one = one[: SIG_MAX_CHARS - 3] + "..."
        out.append(f"L{num} {one}")
    return "\n".join(out)


def main():
    files = sorted(_iter_repo_py_files())
    if not files:
        print("[line-index] no .py files found under the workspace.", file=sys.stderr)
        return 0

    sections = [s for s in (_render_file_section(f) for f in files) if s]
    header = (
        "# Line Index\n"
        "Auto-generated by tools/generate_line_index.py. Do not edit by hand.\n"
        "Format: `L<line> <signature>` per entry, one entry per line.\n"
        "Covers every .py in the workspace except virtualenvs, caches, and build output.\n\n"
    )
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(header + "\n\n".join(sections), encoding="utf-8")
    rel_out = OUTPUT_PATH.relative_to(WORKSPACE_ROOT).as_posix()
    print(f"[line-index] wrote {len(sections)} of {len(files)} file section(s) -> {rel_out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
