"""What is broken in the leaf tier, why, and where the thing it wanted went.

The pytest gate answers pass/fail. This answers "is it worth fixing" — for each
break it names the missing module and, if the reorganisation moved it, where it
lives now. Run it, read it, decide. Nothing here fixes anything.

    python qa/breakage.py
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import sys
from collections import defaultdict
from pathlib import Path

import nativestub
import test_imports

REPO = Path(__file__).resolve().parents[1]
SEARCH_ROOTS = ("Core", "HeroAI", "Widgets", "Scripts", "dev", "Sources", "Runtime")


def build_index() -> dict[str, list[str]]:
    """name -> where anything by that name now lives."""
    index: dict[str, list[str]] = defaultdict(list)
    for root in SEARCH_ROOTS:
        base = REPO / root
        if not base.is_dir():
            continue
        for path in base.rglob("*"):
            if "__pycache__" in path.parts:
                continue
            rel = path.relative_to(REPO).as_posix()
            if path.is_dir():
                index[path.name].append(rel)
            elif path.suffix == ".py":
                index[path.stem].append(rel)
    return index


def load_manifest():
    sys.path.insert(0, str(REPO / "tools" / "reforge"))
    try:
        import manifest as manifest_mod

        return manifest_mod.load()
    except Exception:
        return None


MANIFEST = load_manifest()


def manifest_verdict(module: str) -> str | None:
    """What the manifest did to this path — authoritative, unlike guessing."""
    if MANIFEST is None:
        return None
    prefix = module.replace(".", "/")
    hits = []
    for entry in MANIFEST.entries:
        literal = entry.match.split("*")[0].split("{")[0].rstrip("/")
        if not literal:
            continue
        if literal == prefix or literal.startswith(prefix + "/"):
            hits.append(entry)
    if not hits:
        return None
    entry = min(hits, key=lambda e: len(e.match))
    if entry.dest == "drop":
        return "DROPPED by rule `%s`" % entry.match
    return "`%s` → `%s`" % (entry.match, entry.dest)


def locate(module: str, index: dict[str, list[str]]) -> str:
    verdict = manifest_verdict(module)
    if verdict:
        return verdict
    tail = module.split(".")[-1]
    hits = index.get(tail, [])
    if hits:
        extra = "" if len(hits) == 1 else " (+%d more)" % (len(hits) - 1)
        return "`%s`%s" % (hits[0], extra)
    return "not in the tree — dropped, or never existed"


def failure_of(path: Path):
    try:
        test_imports.load_from_path(path)
    except BaseException as exc:
        return exc
    return None


def missing_module(exc: BaseException) -> str | None:
    if isinstance(exc, ModuleNotFoundError) and exc.name:
        return exc.name
    return None


def collect():
    results = []
    for package in ("Widgets", "Scripts"):
        for path in test_imports.loadable_files(package):
            exc = failure_of(path)
            if exc is not None:
                results.append((path.relative_to(REPO).as_posix(), exc))
    return results


def render(results, index) -> str:
    lines: list[str] = []
    total = len(test_imports.loadable_files("Widgets")) + len(test_imports.loadable_files("Scripts"))
    lines.append("# Leaf breakage")
    lines.append("")
    lines.append("%d of %d widget/script files fail to load." % (len(results), total))
    lines.append("")
    lines.append("Generated by `python qa/breakage.py`. Nothing here is fixed automatically —")
    lines.append("it exists so you can decide what is worth fixing and what should just go.")
    lines.append("")

    by_missing: dict[str, list[str]] = defaultdict(list)
    other: list[tuple[str, BaseException]] = []
    for rel, exc in results:
        name = missing_module(exc)
        if name:
            by_missing[name].append(rel)
        else:
            other.append((rel, exc))

    lines.append("## Missing modules — the reorganisation moved these")
    lines.append("")
    lines.append("| wanted | by | now lives at |")
    lines.append("|---|---|---|")
    for name in sorted(by_missing, key=lambda n: -len(by_missing[n])):
        lines.append("| `%s` | %d | %s |" % (name, len(by_missing[name]), locate(name, index)))
    lines.append("")

    lines.append("## Everything else")
    lines.append("")
    if other:
        lines.append("| file | error |")
        lines.append("|---|---|")
        for rel, exc in sorted(other):
            detail = str(exc).splitlines()[0][:90] if str(exc) else ""
            lines.append("| `%s` | %s: %s |" % (rel, type(exc).__name__, detail))
    else:
        lines.append("None.")
    lines.append("")

    lines.append("## Which files, per missing module")
    lines.append("")
    for name in sorted(by_missing, key=lambda n: -len(by_missing[n])):
        lines.append("**`%s`** → %s" % (name, locate(name, index)))
        lines.append("")
        for rel in sorted(by_missing[name]):
            lines.append("- `%s`" % rel)
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.parse_args()

    nativestub.install()
    results = collect()
    index = build_index()
    report = render(results, index)

    # Importing the tree redirects sys.stdout into the Py4GW console, so the
    # report always goes to a file — printing it would vanish.
    target = REPO / "docs" / "BREAKAGE.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(report + "\n", encoding="utf-8")
    os.write(1, b"wrote docs/BREAKAGE.md (%d broken)\n" % len(results))
    return 0


if __name__ == "__main__":
    sys.exit(main())
